// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UltraCoolBooks.Models;

public partial class AuthorBook
{
    [System.ComponentModel.DataAnnotations.Required]
    public int AuthorId { get; set; }
    [System.ComponentModel.DataAnnotations.Required]
    public int BooksBookId { get; set; }

    public virtual Author Author { get; set; }

    public virtual Book BooksBook { get; set; }
}