// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using UltraCoolBooks.Data;

namespace UltraCoolBooks.Models;

public partial class Book
{
    public int BookId { get; set; }

    public string UserId { get; set; }
    [System.ComponentModel.DataAnnotations.Required]
    public string Title { get; set; }
    [System.ComponentModel.DataAnnotations.Required]
    public string Description { get; set; }
    [System.ComponentModel.DataAnnotations.Required]
    public string ISBN { get; set; }
    [System.ComponentModel.DataAnnotations.Required]
    public string ImagePath { get; set; }

    public bool? isDeleted { get; set; }

    public DateTime Created { get; set; }
    [System.ComponentModel.DataAnnotations.Required]
    public DateTime ReleaseDate { get; set; }

    public virtual ICollection<AuthorBook> AuthorBooks { get; } = new List<AuthorBook>();

    public virtual ICollection<BookGenre> BookGenres { get; } = new List<BookGenre>();

    public virtual ICollection<Review> Reviews { get; } = new List<Review>();

    public virtual UltraCoolUser User { get; set; }
}