// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using UltraCoolBooks.Data;

namespace UltraCoolBooks.Models;

public partial class Review
{
    public int ReviewId { get; set; }

    public string UserId { get; set; }

    public string Title { get; set; }

    public int Rating { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime Created { get; set; }

    // This property should not be added to the database
    [NotMapped]
    public string CreatedTimeAgo { get; set; }

    public int BookId { get; set; }

    [System.ComponentModel.DataAnnotations.Required]
    public string ReviewText { get; set; }

    public int Likes { get; set; }
    public int FLaggedCount { get; set; }

    public int Downvotes { get; set; }

    public int Upvotes { get; set; }

    public virtual Book Book { get; set; }

    public virtual ICollection<ReviewFeedBack> ReviewFeedBacks { get; } = new List<ReviewFeedBack>();
    public virtual ICollection<ReviewComment> ReviewComments { get; } = new List<ReviewComment>();

    public virtual UltraCoolUser User { get; set; }
}