// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using UltraCoolBooks.Data;

namespace UltraCoolBooks.Models;

public partial class ReviewFeedBack
{
    public int ReviewFeedBackId { get; set; }

    public bool? IsHelpful { get; set; }

    public string UserId { get; set; }

    public int ReviewId { get; set; }

    public bool? HasFlagged { get; set; }

    public virtual Review? Review { get; set; }
    public virtual UltraCoolUser User { get; set; }
}